# Dockerfile-postgres

# Usando a imagem oficial do PostgreSQL
FROM postgres:16-alpine

# Configuração das variáveis de ambiente para inicialização do PostgreSQL
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD Senha48
ENV POSTGRES_DB tc_soat4_g48

# Copie scripts de inicialização personalizados, se necessário (opcional)
# COPY ./scripts/ /docker-entrypoint-initdb.d/
