INSERT INTO produtos
    (codigo, nome, descricao, preco, situacao, categoria)
VALUES
    ('69e3f2a1-ee20-4c4c-a3c5-87c85fe4efa8', 'Hambúrguer Simples', 'Hambúrguer de carne 150g com queijo e alface', 20.0, 'DISPONIVEL', 'LANCHE'),
    ('a661bb36-4dab-4c0f-8d40-6a9bea5c6fc7', 'Hambúrguer Vegetariano', 'Hambúrguer de grão de bico 150g com queijo e alface', 21.0, 'DISPONIVEL', 'LANCHE'),
    ('1494d828-4a41-46de-a340-fea1ff79cd63', 'Hambúrguer Duplo', '2 Hambúrgueres de carne 150g com queijo, alface e tomate', 30.0, 'DISPONIVEL', 'LANCHE'),
    ('20b31e71-cfa6-4833-aa04-16b91ebb3488', 'Hambúrguer de Frango', 'Hambúrguer de frango 150g com molho especial', 22.0, 'DISPONIVEL', 'LANCHE'),
    ('756308a5-fc66-4223-bdf4-dbc64366a50b', 'Hambúrguer Picanha', 'Hambúrguer de picanha 180g com queijo prato', 25.0, 'DISPONIVEL', 'LANCHE'),
    ('bf385ed8-5c2d-4fd1-b37d-6c141589a4be', 'Hambúrguer de Peixe', 'Hambúrguer de peixe 150g com alface e tartar', 23.0, 'DISPONIVEL', 'LANCHE'),
    ('fe91ab2c-289b-4023-9f2d-a2e00056d84d', 'Hambúrguer Bacon', 'Hambúrguer de carne 150g com bacon e cheddar', 24.0, 'DISPONIVEL', 'LANCHE'),
    ('5b4781e6-97ca-4425-a1ac-8151df853f1f', 'Hambúrguer de Cordeiro', 'Hambúrguer de cordeiro 160g com rúcula e tzatziki', 26.0, 'DISPONIVEL', 'LANCHE'),
    ('5fa552da-b9c5-4975-9519-d7e4061eea8a', 'Hambúrguer Texano', 'Hambúrguer de carne 150g com onion rings e barbecue', 24.5, 'DISPONIVEL', 'LANCHE'),
    ('3c2bea4f-7687-4e0a-8c3d-9153fb4eb639', 'Hambúrguer de Carne Seca', 'Hambúrguer de carne 150g com queijo, alface e tomate', 27.0, 'DISPONIVEL', 'LANCHE');
--    (null, 'Sanduíche de Frango', 'Peito de frango grelhado, alface, tomate e maionese', 18.0, 'DISPONIVEL', 'LANCHE'),
--    (null, 'Sanduíche de Atum', 'Atum, alface, tomate, azeitonas e maionese', 19.0, 'DISPONIVEL', 'LANCHE'),
--    (null, 'Sanduíche Vegetal', 'Mix de verduras frescas com molho especial', 17.0, 'DISPONIVEL', 'LANCHE'),
--    (null, 'Wrap de Frango', 'Frango desfiado, alface, tomate, cenoura e molho rosé', 20.0, 'DISPONIVEL', 'LANCHE'),
--    (null, 'Wrap Vegano', 'Hummus, rúcula, tomate, pepino e azeitonas', 19.5, 'DISPONIVEL', 'LANCHE'),
--    (null, 'Hot Dog Simples', 'Salsicha, molho, milho e batata palha', 13.0, 'DISPONIVEL', 'LANCHE'),
--    (null, 'Hot Dog Completo', 'Salsicha, molho, milho, batata palha, queijo e bacon', 15.5, 'DISPONIVEL', 'LANCHE'),
--    (null, 'Taco de Carne', 'Taco com carne moída, alface, tomate, queijo e molho picante', 16.0, 'DISPONIVEL', 'LANCHE'),
--    (null, 'Taco de Frango', 'Taco com frango desfiado, alface, tomate, queijo e sour cream', 16.0, 'DISPONIVEL', 'LANCHE'),
--    (null, 'Burrito Vegano', 'Arroz, feijão, cenoura, tomate, azeitonas e molho especial', 20.0, 'DISPONIVEL', 'LANCHE'),
--    (null, 'Burrito de Carne', 'Arroz, carne moída, tomate, queijo e molho especial', 22.0, 'DISPONIVEL', 'LANCHE'),
--    (null, 'Burrito de Frango', 'Arroz, frango desfiado, tomate, queijo e molho especial', 23.0, 'DISPONIVEL', 'LANCHE'),
--    (null, 'Batata Frita', '250g de pura batata', 15.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Batata Frita com Cheddar', '250g de batata coberta com cheddar', 17.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Batata Frita com Bacon', '250g de batata coberta com pedaços de bacon', 18.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Onion Rings', 'Anéis de cebola empanados e fritos', 16.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Anéis de Lula', 'Anéis de lula empanados', 20.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Mandioca Frita', '250g de mandioca frita e crocante', 15.5, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Polenta Frita', 'Tiras de polenta frita', 14.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Salada Verde', 'Mix de folhas verdes, tomate e pepino', 12.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Salada Caesar', 'Alface, croutons, frango grelhado e molho Caesar', 19.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Coleslaw', 'Salada de repolho e cenoura com molho agridoce', 13.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Picles', 'Porção de picles em conserva', 8.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Guacamole', 'Pasta de abacate temperada', 15.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Arroz Branco', 'Porção de arroz branco', 10.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Arroz Carreteiro', 'Arroz com pedaços de carne e legumes', 20.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Feijão Tropeiro', 'Feijão misturado com farinha, bacon e linguiça', 18.5, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Ovo Frito', '2 ovos fritos', 6.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Queijo Coalho', 'Porção de queijo coalho grelhado', 15.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Azeitonas Temperadas', 'Porção de azeitonas temperadas', 9.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Farofa', 'Farofa temperada', 8.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Purê de Batata', 'Purê cremoso de batata', 12.0, 'DISPONIVEL', 'ACOMPANHAMENTO'),
--    (null, 'Refrigerante Lata', 'Lata 350ml', 6.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Refrigerante 600ml', 'Garrafa 600ml', 8.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Suco Natural Laranja', 'Copo de 300ml de suco natural de laranja', 8.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Água Mineral', 'Garrafa 500ml sem gás', 4.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Refrigerante Coca-Cola Lata', 'Lata 350ml de Coca-Cola', 5.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Refrigerante Pepsi Lata', 'Lata 350ml de Pepsi', 4.5, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Refrigerante Guaraná Lata', 'Lata 350ml de Guaraná Antarctica', 4.5, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Refrigerante Sprite Lata', 'Lata 350ml de Sprite', 4.5, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Refrigerante Fanta Lata', 'Lata 350ml de Fanta', 4.5, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Refrigerante Zero Lata', 'Lata 350ml de refrigerante zero açúcar', 5.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Refrigerante Diet Lata', 'Lata 350ml de refrigerante diet', 4.5, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Suco de Laranja Natural', 'Copo de 300ml de suco natural de laranja', 7.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Suco de Maçã Natural', 'Copo de 300ml de suco natural de maçã', 6.5, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Água Mineral com Gás', 'Garrafa 500ml de água com gás', 3.5, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Água Mineral sem Gás', 'Garrafa 500ml de água mineral sem gás', 3.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Água de Coco', 'Garrafa 330ml de água de coco natural', 5.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Chá Gelado de Pêssego', 'Copo 500ml de chá gelado de pêssego', 6.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Chá Gelado de Limão', 'Copo 500ml de chá gelado de limão', 6.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Chá Gelado de Framboesa', 'Copo 500ml de chá gelado de framboesa', 6.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Chá Gelado de Uva', 'Copo 500ml de chá gelado de uva', 6.0, 'DISPONIVEL', 'BEBIDA'),
--    (null, 'Milkshake Chocolate', 'Milkshake cremoso sabor chocolate', 14.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Milkshake Morango', 'Milkshake cremoso sabor morango', 14.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Milkshake Baunilha', 'Milkshake cremoso sabor baunilha', 14.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Milkshake Oreo', 'Milkshake cremoso com biscoitos Oreo', 15.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Milkshake Café', 'Milkshake cremoso sabor café', 13.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Torta de Limão', 'Fatia de torta com recheio de limão', 12.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Sorvete', 'Pote de sorvete sabor baunilha 150g', 10.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Pudim de Leite', 'Pudim de leite condensado', 9.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Brigadeiro', 'Porção de brigadeiros', 8.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Cheesecake de Morango', 'Fatia de cheesecake com calda de morango', 15.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Sorvete de Chocolate', 'Pote de sorvete sabor chocolate', 10.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Torta de Maçã', 'Fatia de torta com recheio de maçã', 12.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Pavê de Chocolate', 'Porção de pavê de chocolate', 11.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Waffle com Sorvete', 'Waffle quente com sorvete e calda de chocolate', 16.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Bolo de Cenoura', 'Fatia de bolo de cenoura com cobertura de chocolate', 10.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Churros', 'Porção de churros com doce de leite', 7.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Sorvete de Morango', 'Pote de sorvete sabor morango 150g', 10.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Mousse de Chocolate', 'Mousse cremoso de chocolate', 9.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Banana Split', 'Banana cortada com sorvete, chantilly e coberturas', 14.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Creme Brulée', 'Creme brulée com açúcar queimado', 12.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Pudim de Chocolate', 'Pudim de chocolate com recheio de chocolate', 11.0, 'DISPONIVEL', 'SOBREMESA'),
--    (null, 'Bolo de Chocolate', 'Fatia de bolo de chocolate com cobertura de ganache', 11.0, 'DISPONIVEL', 'SOBREMESA');
--
--
